name: 8 Conditional workflow
on: workflow_dispatch
jobs:
   step-skip-on-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Install package
        id: fail_skipped_package_install
        run: npm run random
      - name: Echo if the (Install package) fails   #  https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        run:  echo "It should have printed."
   step-not-work-on-fail-without-using-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Fail this step # if this step fails the below step wont work and the Install package step will be skipped. 
                        # ALso the github has a default behaviour that prevent any steps being executed if one step is failed. TO change it, we need to use failure() function. 
        run: juhu v chopati
      - name: Install package
        id: fail_package_install
        run: npm run random
      - name: Echo if the (Install package) fails 
        if: failure() &&  steps.fail_package_install.outcome == 'failure'     # ${{ }} is not needed for if clause. Its an exception for this.   &&&&&&&&     failure() is a special function provided by github. Check the docs  https://docs.google.com/document/d/1dQJC4H0arppjTLWEerSGnX216Top9DV_WXQHctvySmQ/edit#heading=h.j4fxyccdmq4
        run:  echo "It shouldn't have printed."
   step-work-on-fail-using-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      # - name: Echo shit  # if this step fails the below step wont work and the Install package step will be skipped. 
      # ALso the github has a default behaviour that prevent any steps being executed if one step is failed. TO change it, we need to use failure() function. 
      # run: juhu v chopati
      - name: Install package
        id: fail_package_install
        run: npm run random
      - name: Echo if the (Install package) fails 
        if: failure() &&  steps.fail_package_install.outcome == 'failure'     # ${{ }} is not needed for if clause. Its an exception for this.   &&&&&&&&     failure() is a special function provided by github. Check the docs  https://docs.google.com/document/d/1dQJC4H0arppjTLWEerSGnX216Top9DV_WXQHctvySmQ/edit#heading=h.j4fxyccdmq4
        run:  echo "It should have printed."
   step-skipped-on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase 2nd
        uses: actions/checkout@v3
      - name: Install package 2nd
        id: success_package_install
        run: npm i
      - name: Shouldn't echo if the (Install package) succedded 
        if: failure() &&  steps.success_package_install.outcome == 'failure' 
        run:  echo "it shouldn't be printed"
   do-not-proceed-after-job-fail:
    runs-on: ubuntu-latest
    needs: [step-skip-on-fail, step-skipped-on-success ]
    steps:
      - name: Echo if any of the needs job fails
        run:  echo "It should have printed."
   proceed-even-after-job-fail: # run the job even after the job fail using failure()
    runs-on: ubuntu-latest
    needs: [step-skip-on-fail, step-skipped-on-success ]
    if: failure()
    steps:
      - name: Echo if any of the needs job fails
        run:  echo "It should have printed."
   fail-the-job:
    runs-on: ubuntu-latest
    continue-on-error: true 
    steps:
      - name: Fail this
        run: npm run shutup
   proceed-even-after-step-fail-using-continue: # run the job even after the job fail using failure()
    runs-on: ubuntu-latest
    needs: [ fail-the-job ]
    steps:
      - name: Fail this step
        run: npm run shit 
      - name: Echo if any of the needs job fails
        run:  echo "It should have printed."
    