name: 12 Custom JS-Action Workflow usage
on: workflow_dispatch 
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Run Js Custom action.
        uses: ./.github/custom-actions/node-basic-setup.yml