name: 12 Custom JS-Action Workflow usage
on: workflow_dispatch 
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps: 
      # we are using relative path in the run js custom action path. If it had been an external repo, we would have used it without actions/checkout@v3.
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Run Js Custom action.
        #path to the github action folder and not the file.
        uses: ./.github/custom-actions/