name: 7 Env output
on: workflow_dispatch
env:
  ACTION: ${{ github.repository_owner_id }}
  # REPO_SECRET: ${{ secrets.REPO_OWNER }} # REPOSITORY SECRET
  # REPO_VAR:   # REPOSITORY VARIABLE
  # ENV_SECRET: ${{ }} # ENVIRONMENT SECRET
  # ENV_VARIABLE: ${{ }} # ENVIRONMENT VARIABLE

jobs:
   pass-env:
    runs-on: ubuntu-latest
    # env:
    #   OWNER: ${{ env.OWNER }}
    # outputs:
    #   # the below name can be customized.
    #   action-name: ${{ steps.action_name.outputs.ACTION_NAME_ECHO }}
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Get env value
      # the below env is setted up in github https://github.com/deepanshu195/github-actions-learn/settings/environments/1863978320/edit
        run: echo "${{ env.ACTION }}"
      - name: Install package
        run: npm ci
      - name: Echo the variables
        run: echo "${{ toJSON(secrets) }}"
      - name: Echo the Env
        run: echo "${{ toJSON(env) }}"
      - name: Echo the vars
        run: echo " ${{ toJSON(vars) }} "
      - name: Run the value
        run: OWNER=${{ env.ACTION}} npm run start