name: 7 Env output
on: workflow_dispatch
env:
  ACTION: ${{ github.repository_owner_id }}
jobs:
   pass-env:
    runs-on: ubuntu-latest
    # env:
    #   OWNER: ${{ env.OWNER }}
    # outputs:
    #   # the below name can be customized.
    #   action-name: ${{ steps.action_name.outputs.ACTION_NAME_ECHO }}
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Get env value
      # the below env is setted up in github https://github.com/deepanshu195/github-actions-learn/settings/environments/1863978320/edit
        run: echo "${{ env.ACTION }}"
      - name: Install package
        run: npm ci
      - name: Run the value
        run: OWNER=env.ACTION npm run start
      - name: Run the value
        run: OWNER= ${{ toJSON(secrets) }} npm run start        