name: 6 Job output
on: workflow_dispatch
jobs:
   get-name:
    runs-on: ubuntu-latest
    output:
      # the below name can be customized.
      action-name: ${{ steps.action_name.outputs.ACTION_NAME_ECHO }}
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Get action name
      # given the id so that we can refer to the step output 
        id: action_name
        run: echo "ACTION_NAME_ECHO ${{ github.action }} >> $GITHUB_OUTPUT"
   publish-name:
    runs-on: ubuntu-latest
    need: get-name
    steps:
      - name: Print the above output
      # needs context object contains the output values of all the depenedent job for the current job.
        run: echo "${{needs.action-name}}"
    