name: 6 Job output
on: workflow_dispatch
jobs:
   get-name:
    runs-on: ubuntu-latest
    outputs:
      # the below name can be customized.
      action-name: ${{ steps.action_name.outputs.ACTION_NAME_ECHO }}
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Get action name
        run: echo " ${{ github.repository_owner }}"
      - name: Get action name
      # given the id so that we can refer to the step output 
        id: action_name
        echo "BRANCH=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
        run: echo "ACTION_NAME_ECHO=${{ github.repository_owner }}" >> "$GITHUB_OUTPUT"
   publish-name:
    runs-on: ubuntu-latest
    needs: get-name
    steps:
      - name: Print the above output
      # needs context object contains the output values of all the depenedent job for the current job.
        run: echo "${{needs.get-name.outputs.action-name}}"
    