name: Extract Job Artifacts and use them later
on: workflow_dispatch
jobs:
   get-output:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: dist
          path: |
            package.json
            package-lock.json
      - name: Print the github context
        run: echo "${{ toJSON(github) }}"