
name: 3 Node Multiple workflow
on: 
  workflow_dispatch:
  push: 
    branches: master
    paths-ignore: 
      - './.github/workflows/**.yml'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone the repo using github action checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Printing current date
        run: npm run start
  run-script-again:
  #the run-script & run-script-again jobs will exec parallelly. 
    runs-on: ubuntu-latest
    steps: 
      - name: Clone the repo using github action checkout for trying out.
        uses: actions/checkout@v3
      - name: Install dependecies again
        run: npm ci
      - name: Printing current date again
        run: npm run start
  run-script-sequentially:
    runs-on: ubuntu-latest
    # the needs keyword wait for the mentioned job to finish post that only it will start exec.
    needs: run-script
    steps: 
      - name: Clone the repo using github action checkout
        uses: actions/checkout@v3
        #the node js is already installed, as there are some predefined software which are already installed in ubuntu-latest runner.
      - name: Install node js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Printing current date
        run: npm run start
      