name: Extract output
on: workflow_dispatch
jobs:
   get-output:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Print the github context
      # ${{ }} by using this we want to access the variables. github is the reserved keyname. It the also the context which is avaiable.  Please refer to https://docs.github.com/en/actions/learn-github-actions/contexts.
        run: echo "${{ toJSON(github) }}"
