# name: 10 Reusable workflow
# on: workflow_call # this means it will be called from another workflow
# jobs:
#   reusing-job:
#   # the above is a custom name, rest all were keywords. 
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Printing on console
#         run: echo "hello world"
#       - name: Process multi-line cmds
#         run: echo " First Step "

name: 10 Reusable workflow
on: 
  workflow_call: 
    inputs: 
      artifact_name: 
        description: The Name of the artifact
        required: false
        type: string
    secrets:
      artifact_secret_name: 
        description: The Name of the secret artifact
        required: false
    outputs:
      description: This is the ouput for reusable workflow
      value: ${{ jobs.reusing-job.outputs.dummy-output }}

jobs:
  reusing-job:
    runs-on: ubuntu-latest
    outputs:
      dummy-output: ${{ steps.action_name.outputs.ACTION_NAME_ECHO }}
    steps: 
      - name: Printing on console
        run: echo "hello world"
      - name: Process multi-line cmds
        run: echo "${{ inputs.artifact_name }}"
      - name: Print the secrets
        run: echo " ${{ secrets.artifact_secret_name }}"
      - name: print the dummy value output
        id: ACTION_NAME_ECHO
        run: echo"DUMMY_OUTPUT=hh" >> "$GITHUB_OUTPUT"
