name: 11 Reusable workflow usage

on: 
  workflow_dispatch:
    inputs:
      artifact_name: 
        description: The Name of the artifact
        required: false
        default: distnance
        type: string
    secrets:
      artifact_secret_name: 
        description: The Name of the secret artifact
        required: false
        default: secret
        type: string
jobs:
  first_job:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      artifact_name: ${{ inputs.artifact_name }}
    secrets: 
      artifact_secret_name: ${{ inputs.artifact_name }}
  # second-job:
  #   runs-on: ubuntu-latest
  #   needs: first_job
  #   steps:
  #     - name: Echo the inputs
  #       run: echo " ${{ needs.first_job.outputs.result }}"