name: 11 Reusable workflow usage

on: 
  workflow_dispatch:
    inputs:
      artifact_name: 
        description: The Name of the artifact
        required: false
        default: distnance
        type: string

jobs:
  first_job:
    uses: ./.github/workflows/reusable-workflow.yml
  second-job:
    steps:
      - name: Echo the input
        run: echo " ${{ input.artifact_name }}"