
name: 9 Extract context
on: workflow_dispatch
jobs:
   get-output:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 12, 14, 16 ]
        operating-system: [ ubuntu-latest , windows-latest ]
        include: # add stand along combination
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # substract the combination
          - node-version: 12
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Echo something 
        run: echo "${{ matrix.operating-system }}"