name: 5 Upload and Download the builds
on: workflow_dispatch
jobs:
   upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: dist
          path: |
            package.json
            package-lock.json
      - name: Print the github context
        run: echo "${{ toJSON(github) }}"
   download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Check for artifact
        run: ls

    